# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password 

    ports:
      - 3306:3306

    volumes:
      - ./docker/scripts:/docker-entrypoint-initdb.d
    



  app:
    build: .

    ports:
      - 80:80

    environment:
      HOST: "0.0.0.0"
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASSWORD: "password" 
      DB_DATABASE: "tnexus"

    expose:
      - 80
    
    depends_on:
      - db
