/**
 * This Endpoint return a JSON with all components
 * Uses the function getComponents in components services
 */

// Imports
import type { APIRoute } from "astro";
import { getComponents, addComponent } from "@services/components";

// REST API Route

// GET
export const GET: APIRoute = () => {
  // Create the response with the data that the service returned (the JSON itself)

  // API Response
  return new Response(JSON.stringify(getComponents()));
};

// POST
export const POST: APIRoute = async ({ request }) => {
  // If the POST body is not a JSON
  if (request.headers.get("Content-Type") === "application/json") {
    // Getting the JSON
    const body = await request.json();
    // Component object
    const component = {
      id: "Generated by DB",
      name: body.name,
      description: body.description,
      thumbnail: "Generated?",
      tailwind: String(body.tailwind),
      javascript: String(body.javascript).replaceAll('"', '\\"'),
      needsAlpine: body.needsAlpine,
      needsCDN: body.needsCDN,
      createdAt: new Date(),
      updatedAt: new Date(),
      categoryId: body.categoryId,
      userId: body.userId,
    };
    return new Response(JSON.stringify(addComponent(component) || []));
  }
  return new Response(null, { status: 400 });
};
